name: Enocraft-plugin
author: Kimit
version: 1.0
main: com.kimit.enocraft.Main
api-version: 1.17

commands:
  setshop:
    description: Set shop location
    usage: /<command>
    permission: enocraft.shop.setshop
  shop:
    description: Teleport to shop
    usage: /<command>
    permission: enocraft.shop.shop
  stock:
    description: Open stock
    usage: /<command>
    permission: enocraft.stock
  dragonegg:
    description: Regulate stock price when dragon egg.
    usage: /<command> <number>
    permission: enocraft.dragonegg
  playerinfo:
    description: Show player info.
    usage: /<command> <nickname>
    permission: enocraft.playerinfo
  send:
    description: Send player money.
    usage: /<command> <nickname> <money>
    permission: enocraft.send
  market:
    description: Market command.
    usage: /<command> <send|open|receive>
    permission: enocraft.market
  constant:
    description: Get/set constant.
    usage: /<command> <get|set> <constant>
    permission: enocraft.constant